ALTER TABLE announcements
ADD COLUMN IF NOT EXISTS body_html TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS body_json JSONB NOT NULL DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS target_level_id UUID REFERENCES levels(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS published_at TIMESTAMPTZ;
